#!/bin/bash

# Check if arguments are provided
if [ $# -ne 2 ]; then
    echo "Usage: ./run.sh <np> <N>"
    exit 1
fi

# Number of processes
NP=$1

# Parameter N
N=$2

# Paths to config
PLATFORM_FILE=config/platform.xml
HOSTFILE=config/hostfile.txt

# Check if platform.xml and hostfile.txt exist
if [ ! -f "$PLATFORM_FILE" ] || [ ! -f "$HOSTFILE" ]; then
    echo "Error: Missing platform.xml or hostfile.txt in config directory."
    exit 1
fi

# Build the program
make all

# Check if build was successful
if [ $? -eq 0 ]; then
    echo "Build successful. Running the program..."
    # Run the program with smpirun
    docker run --rm -it -v $(pwd):/home/smpi --user $(id -u):$(id -g) henricasanova/ics632_smpi \
        smpirun -platform $PLATFORM_FILE -hostfile $HOSTFILE -np $NP ./build/julia_mpi $N
else
    echo "Build failed. Please check the errors."
    exit 1
fi
